stages:
  acquire:
    cmd: poetry run python data_pipeline/acquire.py
    outs:
    - data/raw/2020_01/SCDB_2020_01_caseCentered_Citation.sav:
        persist: true
    - data/raw/2020_01/SCDB_2020_01_caseCentered_Docket.sav:
        persist: true
    - data/raw/2020_01/SCDB_2020_01_caseCentered_LegalProvision.sav:
        persist: true
    - data/raw/2020_01/SCDB_2020_01_caseCentered_Vote.sav:
        persist: true
    - data/raw/2020_01/SCDB_2020_01_justiceCentered_Citation.sav:
        persist: true
    - data/raw/2020_01/SCDB_2020_01_justiceCentered_Docket.sav:
        persist: true
    - data/raw/2020_01/SCDB_2020_01_justiceCentered_LegalProvision.sav:
        persist: true
    - data/raw/2020_01/SCDB_2020_01_justiceCentered_Vote.sav:
        persist: true
    - data/raw/Legacy_06/SCDB_Legacy_06_caseCentered_Citation.sav:
        persist: true
    - data/raw/Legacy_06/SCDB_Legacy_06_justiceCentered_Citation.sav:
        persist: true
  featherize:
    cmd: poetry run python data_pipeline/featherize.py
    deps:
    - data/raw/
    outs:
    - data/feathers/
  wrangle:
    cmd: poetry run python data_pipeline/wrangle.py
    deps:
    - data/feathers/
    outs:
    - data/processed/SCDB_Legacy-and-2020r1_caseCentered_Citation.feather
