stages:
  acquire:
    cmd: poetry run python data_pipeline/acquire.py
    outs:
    - data/raw/scdb/2020_01/caseCentered_Citation.sav:
        persist: true
    - data/raw/scdb/2020_01/caseCentered_Docket.sav:
        persist: true
    - data/raw/scdb/2020_01/caseCentered_LegalProvision.sav:
        persist: true
    - data/raw/scdb/2020_01/caseCentered_Vote.sav:
        persist: true
    - data/raw/scdb/2020_01/justiceCentered_Citation.sav:
        persist: true
    - data/raw/scdb/2020_01/justiceCentered_Docket.sav:
        persist: true
    - data/raw/scdb/2020_01/justiceCentered_LegalProvision.sav:
        persist: true
    - data/raw/scdb/2020_01/justiceCentered_Vote.sav:
        persist: true
    - data/raw/scdb/Legacy_06/caseCentered_Citation.sav:
        persist: true
    - data/raw/scdb/Legacy_06/justiceCentered_Citation.sav:
        persist: true
  featherize:
    cmd: poetry run python data_pipeline/featherize.py
    deps:
    - data/raw/scdb
    outs:
    - data/interim/scdb
  wrangle:
    cmd: poetry run python data_pipeline/wrangle.py
    deps:
    - data/interim/scdb
    outs:
    - data/processed/scdb/SCDB_Legacy-and-2020r1_caseCentered_Citation.feather
